// Pulls the repo's untouched static folders (games/, files/, assets/, img/, CNAME)
// into public/ so they ship in the build. These directories belong to other
// systems (launcher auto-update, the game distribution CDN paths) and must
// never be edited here — this only copies them, never the other direction.
import { existsSync, cpSync, copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = dirname(webRoot);
const publicDir = join(webRoot, "public");

mkdirSync(publicDir, { recursive: true });

const dirs = ["games", "files", "assets", "img"];
for (const dir of dirs) {
  const src = join(repoRoot, dir);
  const dest = join(publicDir, dir);
  if (existsSync(src)) {
    cpSync(src, dest, { recursive: true });
    console.log(`synced ${dir}/`);
  }
}

const files = ["CNAME", "maintainance.html"];
for (const file of files) {
  const src = join(repoRoot, file);
  const dest = join(publicDir, file);
  if (existsSync(src)) {
    copyFileSync(src, dest);
    console.log(`synced ${file}`);
  }
}

// ── Versions ────────────────────────────────────────────────────────────────
//
// The versions shown on the site are DERIVED from the same manifests the
// updaters read, never typed in beside them.
//
// They had drifted three ways at once: the projects list said Linkage v1.2.0,
// the downloads list said v1.4.0, and the published APK was 1.5.0. The
// launcher's own changelog says it too — "Fixed the version number shown in
// the Launcher not matching the actual installed version" — so this is the
// third time the same class of mistake has been fixed by hand.
//
// Hand-edited numbers in two places drift. Generated ones cannot: this runs on
// prebuild, so a stale site version would have to survive a build that
// overwrites it.
const manifests = {
  linkage: { file: "Linkage_version.json", key: "version" },
  launcher: { file: "launcher_version.json", key: "latestVersion" },
};

const versions = {};
for (const [name, { file, key }] of Object.entries(manifests)) {
  const src = join(repoRoot, "files", file);
  if (!existsSync(src)) {
    console.warn(`no ${file} — leaving ${name} version unset`);
    continue;
  }
  try {
    versions[name] = JSON.parse(readFileSync(src, "utf8"))[key] ?? null;
  } catch (err) {
    // A malformed manifest must fail the build rather than silently ship a
    // site claiming a version nobody can download.
    throw new Error(`${file} is not valid JSON: ${err.message}`);
  }
}

const generatedDir = join(webRoot, "src", "generated");
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  join(generatedDir, "versions.js"),
  `// GENERATED by scripts/sync-static.mjs on every build — do not edit.
` +
    `// Source of truth: files/*_version.json, the same manifests the updaters read.
` +
    `export const versions = ${JSON.stringify(versions, null, 2)};
`,
);
console.log(
  "generated src/generated/versions.js:",
  Object.entries(versions).map(([k, v]) => `${k}=${v}`).join(" "),
);
